repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-docstring-first
      - id: trailing-whitespace
      - id: check-yaml
        exclude: ^(docs/|scripts/|alembic/|.gitlab/|.pytest_cache/|.cache)
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: ^(docs/|scripts/|alembic/|.gitlab/|.pytest_cache/|.cache)
      - id: check-added-large-files
      - id: check-json
        exclude: ^(docs/|scripts/|alembic/|.gitlab/|.pytest_cache/|.cache)
      - id: check-merge-conflict
  - repo: https://github.com/PyCQA/flake8
    rev: '4.0.1'
    hooks:
      - id: flake8
        args: ['--max-line-length', '200', '--ignore', 'E128,E126,E121,E123']
        additional_dependencies: [flake8-typing-imports==1.9.0]
        exclude: ^(docs/|scripts/|alembic/|.gitlab/|.pytest_cache/|.cache)
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
        exclude: ^(docs/|scripts/|alembic/|.gitlab/|.pytest_cache/|.cache)
