version: "3.9"

services:
  omma-postgres:
    image: postgres:latest
    container_name: omma-postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - TZ=Europe/Frankfurt
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${COLLECTION_NAME}
    volumes:
      - ./scripts/init-scripts:/code/scripts/init-scripts
      - ./data/postgres_storage:/var/lib/postgresql/data
      - ./data:/code/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h omma-postgres -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  omma-tool-api:
    build: .
    container_name: omma-tool-api
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - TZ=Europe/Frankfurt
    volumes:
      - ./data:/code/data
      - ./scripts/init-scripts:/code/scripts/init-scripts
    entrypoint: ["/code/scripts/init-scripts/init-alembic.sh"]
    command: hypercorn backend.main:app --bind 0.0.0.0:8000 --workers ${PLATFORM_API_WORKERS:-1} --log-level info
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h neural-api-postgres -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  omma-data:
