name: Build and Lint

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  linter:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      run: echo "PATH=/usr/bin:$PATH" >> $GITHUB_ENV

    - name: Update and Install python3-full
      continue-on-error: true
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-full

    - name: Create Virtual Environment
      run: python3.11 -m venv .venv

    - name: Activate Virtual Environment
      run: echo ".venv/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        python3.11 -m pip install --upgrade pip
        pip install pre-commit

    - name: Find pre-commit
      run: |
        echo "Pre-commit location: $(which pre-commit)"

    - name: Run linter
      run: |
        pre-commit install
        pre-commit run --all-files
